# Generated by Django 5.2.6 on 2025-09-30 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='InformationSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistamineInfo',
            fields=[
                ('food', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='foods.food')),
                ('compatibility_score', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('unknown', 'unknown')], default='unknown', max_length=10)),
                ('rapid_histamine_formation', models.CharField(choices=[('true', 'true'), ('false', 'false'), ('unknown', 'unknown')], default='unknown', max_length=10)),
                ('other_amines', models.CharField(choices=[('true', 'true'), ('false', 'false'), ('unknown', 'unknown')], default='unknown', max_length=10)),
                ('liberator', models.CharField(choices=[('true', 'true'), ('false', 'false'), ('unknown', 'unknown')], default='unknown', max_length=10)),
                ('blocker', models.CharField(choices=[('true', 'true'), ('false', 'false'), ('unknown', 'unknown')], default='unknown', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('information_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='foods.informationsource')),
            ],
        ),
        migrations.CreateModel(
            name='FoodName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=250)),
                ('is_primary', models.BooleanField(default=False)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foods.food')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('food', 'language', 'name'), name='uniq_foodname'), models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('food', 'language'), name='uniq_primary_foodname')],
            },
        ),
    ]
