# Generated by Django 5.2.6 on 2025-10-02 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FoodTypeRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foods.food')),
                ('food_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foods.foodtype')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('food', 'food_type'), name='uniq_food_foodtype')],
            },
        ),
    ]
